#'
#'
#' @param database The matrix generated by the creazionedati function.
#' @param K A vector with the cluster that you want consider.
#' @param H A vector with the space dimensions h that you want consider.
#' @return The matrixes in which are stored the AIC and Bic values for each model,
#'         and a list with the output of the Functional Clustering with the different inputs.
#' @examples
#'
#' path <-".../1864_no_P7.csv"
#' Nmice<-24
#' database <- creazionedati(path,Nmice,tr.day)
#' K<-c(4,5,6)
#' H<-c(1,2)
#' Cluster_choice(database,K,H)
#'
#' @import
#' @export


Cluster_choice<-function(database,K,H)
{

  output_k<-list()
  row_names <-c(paste("k=",K))
  col_names<-c(paste("h=",H))
  matrix_AIC<-matrix(0,nrow = length(K),ncol = length(H),dimnames=list(row_names,col_names))
  matrix_BIC<-matrix(0,nrow = length(K),ncol = length(H),dimnames=list(row_names,col_names))

  # return a list of K lists, in which is is stored the output for all h
  # We also create two matrixes with the BIC and AIC values
  for(k in K)
  {
    output_h<-list()
    for(h in H)
    {
      data.funcit <-matrix(c(database$curve.tr,database$x.tr,database$time.tr),ncol=3,byrow=F)
      mycontfclust = new("funcyCtrl",baseType="splines",dimBase=5,init="kmeans",nrep=10,redDim=h)
      output_h[[paste("h=",h)]]<- funcit(data.funcit,seed=2404,k,methods="fitfclust",funcyCtrl=mycontfclust,save.data=TRUE)
      matrix_BIC[which(K==k),which(H==h)]<-output_h[[paste("h=",h)]]@models$fitfclust@BIC
      matrix_AIC[which(K==k),which(H==h)]<-output_h[[paste("h=",h)]]@models$fitfclust@AIC
    }
    output_k[[paste("k=",k)]]<-output_h
  }

  return(list(output_k,matrix_BIC,matrix_AIC))
}
